### ISSUE TITLE
Transcoder API link in docs is broken

### ISSUE THREAD

**Issue by BryanWBear** [googleapis/python-video-transcoder#8]
The following link https://cloud.google.com/transcoder/docs leads to 404 path (step 3 of Quickstart).

**Comment by danoscarmike** [comment]
@BryanWBear this is obviously a bit late but can you tell us a bit more (or if this is still an issue)?

I'm not finding a broken link in the quickstart right now.

**Comment by parthea** [comment]
Hi @BryanWBear ,

I'm going to close this issue as obsolete but please re-open it if you're still seeing the broken link.
